groups:
- name: demo
  rules:

  # Alert for any instance that is unreachable for >2 minutes.
  - alert: service_down
    expr: up == 0
    for: 1m
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minutes."

  - alert: high_load
    expr: node_load1 > 0.5 ##指1分鐘內cpu平均負載
    for: 2m
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} under high load"
      description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."


  - alert: TooManyReq
    expr: request_count_total > 100
    for: 10s
    labels:
      user: test
    annotations:
      summary: "request_count_total is too over!"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has over 100 for more than 1 sec."


  - alert: TriggerExceptions
    expr: request_exceptions_total > 5
    for: 20s
    labels:
      user: test
    annotations:
      summary: "Trigger Exceptions in web-flask 5000/exceptions!"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has exceptions over 3 for more than 5 sec."


  - alert: Latency_calltime
    expr: hello_world_latency_seconds_sum > 4
    for: 20s
    labels:
      user: test
    annotations:
      summary: "Create Latency in web_flask 5000/calltime!"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has latency over 4s for more than 1 min."